KEYS = {
  '38':        {   action: 'move', params: { direction: 'n'  }  },
  '39':        {   action: 'move', params: { direction: 'e'  }  },
  '40':        {   action: 'move', params: { direction: 's'  }  },
  '37':        {   action: 'move', params: { direction: 'w'  }  },
  '38_39':     {   action: 'move', params: { direction: 'ne' }  },
  '39_40':     {   action: 'move', params: { direction: 'se' }  },
  '37_40':     {   action: 'move', params: { direction: 'sw' }  },
  '37_38':     {   action: 'move', params: { direction: 'nw' }  },
  '32_38':     {   action: 'move_atk', params: { direction: 'n' } },
  '32_39':     {   action: 'move_atk', params: { direction: 'e' } },
  '32_40':     {   action: 'move_atk', params: { direction: 's' } },
  '32_37':     {   action: 'move_atk', params: { direction: 'w' } },
  '32_38_39':  {   action: 'move_atk', params: { direction: 'ne' }  },
  '32_39_40':  {   action: 'move_atk', params: { direction: 'se' }  },
  '32_37_40':  {   action: 'move_atk', params: { direction: 'sw' }  },
  '32_37_38':  {   action: 'move_atk', params: { direction: 'nw' }  },
  '38_69':     {   action: 'move_use', params: { direction: 'n'  }  },
  '69':        {   action: 'use' },
  '39_69':     {   action: 'move_use', params: { direction: 'e'  }  },
  '40_69':     {   action: 'move_use', params: { direction: 's'  }  },
  '37_69':     {   action: 'move_use', params: { direction: 'w'  }  },
  '38_39_69':  {   action: 'move_use', params: { direction: 'ne' }  },
  '39_40_69':  {   action: 'move_use', params: { direction: 'se' }  },
  '37_40_69':  {   action: 'move_use', params: { direction: 'sw' }  },
  '37_38_69':  {   action: 'move_use', params: { direction: 'nw' }  },
};
